routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'PageController@index')->name('index');

//Новости
Route::group(['namespace' => 'News', 'as' => 'news.', 'prefix' => 'news'], function() {
    Route::get('/', 'NewsController@index')->name('index');
    Route::get('section/{id}', 'NewsController@section')->name('section');
    Route::post('add', 'NewsController@create')->name('create');
    Route::post('test', 'NewsController@test')->name('test');
    Route::put('update/{id}', 'NewsController@update')->name('update');
    Route::get('{id}', 'NewsController@news')->name('news');
});

//Объявления
Route::group(['namespace' => 'Ad', 'as' => 'ads.', 'prefix' => 'ads'], function() {
    Route::get('/', 'AdController@index')->name('index');
    Route::get('add', 'AdController@add')->name('add');
    Route::post('add', 'AdController@create')->name('create');
    Route::put('edit/{id}', 'AdController@update')->name('update');
    Route::get('category/{category_id}', 'AdController@category')->name('category');
    Route::get('ad/{id}', 'AdController@ad')->name('ad');
});

// Мероприятния
Route::group(['namespace' => 'Event', 'as' => 'events.', 'prefix' => 'events'], function() {
    Route::get('/', 'EventController@index')->name('index');
    Route::get('section/{section_id}', 'EventController@section')->name('section');
    Route::get('event/{id}', 'EventController@event')->name('event');
});

//Форум
Route::group(['as' => 'forum.', 'prefix' => 'forum', 'namespace' => 'Forum'], function() {
    Route::get('/', 'TopicController@index')->name('index');
    Route::get('add', 'TopicController@add')->name('add');
    Route::post('add', 'TopicController@create')->name('create');
    Route::get('topic/{id}', 'TopicController@topic')->name('topic');
    Route::post('topic/{id}', 'TopicController@create_message')->name('create_message');
});

Route::get('road', 'PageController@road')->name('road');
Route::get('bus', 'PageController@bus')->name('bus');
Route::get('weather', 'PageController@weather')->name('weather');
Route::get('aero', 'PageController@aero')->name('aero');
Route::get('afisha', 'PageController@afisha')->name('afisha');

//Администрация
Route::group(['as' => 'administration.', 'prefix' => 'administration'], function() {
    Route::get('/', 'AdministrationController@index')->name('index');
    Route::get('complaint', 'AdministrationController@complaint')->name('complaint');
    Route::post('complaint', 'AbuseFormController@mail_to_administration')->name('mail_to_administration');
    Route::group(['prefix' => 'measure', 'as' => 'measure.'], function() {
        Route::get('/', 'AdministrationController@measures')->name('index');
        Route::get('show/{id}', 'AdministrationController@measure')->name('show');
    });
});

//Архив
Route::group(['as' => 'archive.', 'prefix' => 'archive'], function() {
    Route::get('/', 'ArchiveController@index')->name('index');
    Route::get('upload', 'ArchiveController@upload')->name('upload.file');
    Route::get('mayak', 'ArchiveController@mayak')->name('mayak');
    Route::get('mayak/{id}', 'ArchiveController@show_mayak')->name('show_mayak');
    Route::get('add', 'ArchiveController@add')->name('add');
    Route::post('add', 'ArchiveController@create')->name('create');
    Route::get('section/{id}', 'ArchiveController@section')->name('section');
});

//Лк
Route::group(['prefix' => 'lk', 'as' => 'lk.', 'middleware' => 'auth'], function() {
    Route::get('/', 'UserController@index')->name('index');
    Route::put('/', 'UserController@update')->name('update');
    Route::get('news', 'UserController@news')->name('news');
    Route::get('ads', 'UserController@ads')->name('ads');
    Route::get('events', 'UserController@events')->name('events');
    Route::get('balance', 'UserController@balance')->name('balance');
    Route::get('traffic_info', 'UserController@traffic_info')->name('traffic_info');
    Route::get('tariff', 'UserController@tariff')->name('tariff');
    Route::post('tariff', 'UserController@change_tariff')->name('change_tariff');
    Route::get('documents', 'UserController@documents')->name('documents');
    Route::post('yandex_pay', 'UserController@yandex_pay')->name('yandex_pay');
});


Route::post('ckeditor/image_upload', 'CKEditorController@upload')->name('upload.image');
Route::get('download/{id}', 'PageController@download_file')->name('download_file');

Route::group(['prefix' => 'comment', 'as' => 'comment.'], function() {
    Route::post('add', 'CommentController@create')->name('create');
});

//Админка
Route::group(['prefix' => 'admin', 'as' => 'admin.'], function(){
    Route::get('/', 'AdminController@index')->name('index');

    Route::group(['namespace' => 'Admin'], function() {
        //Новости
        Route::group(['prefix' => 'news', 'as' => 'news.'], function() {
            Route::get('all', 'NewsController@all')->name('all');
            Route::get('/', 'NewsController@new')->name('new');
            Route::get('edit/{id}', 'NewsController@edit')->name('edit');
            Route::delete('{id}', 'NewsController@delete')->name('delete');
            //Категории новостей
            Route::group(['prefix' => 'category', 'as' => 'category.'], function(){
                Route::get('/', 'NewsController@all_categories')->name('all');
                Route::post('/', 'NewsController@create_category')->name('create');
                Route::get('{id}', 'NewsController@edit_category')->name('edit');
                Route::put('{id}', 'NewsController@update_category')->name('update');
                Route::delete('{id}', 'NewsController@delete_category')->name('delete');
            });
            //Теги новостей
            Route::group(['prefix' => 'tags', 'as' => 'tags.'], function(){
                Route::get('/', 'NewsController@all_tags')->name('all');
                Route::post('new', 'NewsController@create_tag')->name('create');
                Route::delete('{id}', 'NewsController@delete_tag')->name('delete');
            });
            //Секции новостей
            Route::group(['prefix' => 'sections', 'as' => 'sections.'], function(){
                Route::get('/', 'NewsController@all_sections')->name('all');
                Route::post('new', 'NewsController@create_section')->name('create');
                Route::delete('{id}', 'NewsController@delete_section')->name('delete');
            });
        });

        //Объявления
        Route::group(['prefix' => 'ads', 'as' => 'ads.'], function(){
            Route::get('all', 'AdsController@all')->name('all');
            Route::get('/', 'AdsController@new')->name('new');
            Route::get('edit/{id}', 'AdsController@edit')->name('edit');
            Route::delete('{id}', 'AdsController@delete')->name('delete');
            //Категории объявлений
            Route::group(['prefix' => 'categories', 'as' => 'categories.'], function(){
                Route::get('/', 'AdsController@all_categories')->name('all');
                Route::post('/', 'AdsController@create_category')->name('create');
                Route::delete('{id}', 'AdsController@delete_category')->name('delete');
            });
            //Города объявлений
            Route::group(['prefix' => 'cities', 'as' => 'cities.'], function(){
                Route::get('/', 'AdsController@all_cities')->name('all');
                Route::post('new', 'AdsController@create_city')->name('create');
                Route::delete('{id}', 'AdsController@delete_city')->name('delete');
            });
        });

        //Мероприятия
        Route::group(['prefix' => 'events', 'as' => 'events.'], function(){
            Route::get('all', 'EventsController@all')->name('all');
            Route::get('/', 'EventsController@new')->name('new');
            Route::post('/', 'EventsController@create')->name('create');
            Route::get('edit/{id}', 'EventsController@edit')->name('edit');
            Route::put('edit/{id}', 'EventsController@update')->name('update');
            Route::delete('{id}', 'EventsController@delete')->name('delete');

            //Категории мероприятий
            Route::group(['prefix' => 'categories', 'as' => 'categories.'], function(){
                Route::get('/', 'EventsController@all_categories')->name('all');
                Route::post('/', 'EventsController@create_category')->name('create');
                Route::get('{id}', 'EventsController@edit_category')->name('edit');
                Route::put('{id}', 'EventsController@update_category')->name('update');
                Route::delete('{id}', 'EventsController@delete_category')->name('delete');
            });

            //Секции новостей
            Route::group(['prefix' => 'sections', 'as' => 'sections.'], function(){
                Route::get('/', 'EventsController@all_sections')->name('all');
                Route::post('new', 'EventsController@create_section')->name('create');
                Route::delete('{id}', 'EventsController@delete_section')->name('delete');
            });
        });

        //Пользователи
        Route::group(['prefix' => 'users', 'as' => 'users.'], function() {
            Route::get('/', 'UsersController@all')->name('all');
            Route::get('edit/{id}', 'UsersController@edit')->name('edit');
            Route::put('edit/{id}', 'UsersController@update')->name('update');
            Route::delete('delete/{id}', 'UsersController@delete')->name('delete');
        });

        //Группы
        Route::group(['prefix' => 'groups', 'as' => 'groups.'], function() {

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    protected $connection = 'mysql2';
    protected $table = 'stat';
    protected $primaryKey = 'shortguid';
    public $incrementing = false;
    public $timestamps = false;

    protected $fillable = [
        'name', 'email', 'password', 'first_name', 'last_name', 'middle_name', 'date_birth', 'photo_id'
    ];

    protected $hidden = [
        'password', 'remember_token', 'user_pswd'
    ];

    public $dates = [
        'date_birth'
    ];

    public function getIdAttribute()
    {
        return $this->shortguid;
    }

    public function group()
    {
        return $this->belongsTo(Group::class);
    }

    public function hasPermission($permission)
    {
        if($this->group_id == 0) return false;
        return $this->group->hasPermission($permission);
    }

    public function moneys()
    {
        return \DB::connection('mysql2')->table('moneys')->where('user_name', $this->shortguid)->get();
    }

    public function tariffs()
    {
        return \DB::connection('mysql2')->table('tarifs')->get();
    }

    public function city()
    {
        return $this->setConnection('mysql')->belongsTo(City::class);
    }

    public function files()
    {
        return $this->connection('mysql')->hasMany(\App\Archive\File::class);
    }

    public function getPhotoAttribute()
    {
        return $this->photo_id;
    }

    public function getTitleDevice($ip)
    {
        $device = \App\Device::find($ip);
        if($device) {
            return $device->title;
        }
        return '';
    }

    public function getDevicesAttribute()
    {
        $devices = explode(';', $this->usrip);
        $collect = collect();
        foreach ($devices as $key => $item) {
            $device = null;
            if($item != '' && $item != null) {
                $device = \App\Device::find($item);
                $traffic = $this->getTrafficDevice($key);
                $n = [
                    'ip' => $item,
                    'title' => $device ? $device->title : 'Без названия',
                    'type' => $device ? $device->type : 0,
                    'traffic' => isset($traffic[$key]) ? $traffic[$key] : 0
                ];
                $collect = $collect->push($n);
            }
        }
        return $collect;
    }

    public function getTrafficDevice()
    {
        $startDate = now()->subMonth();
        $endDate = now();
        $traffics = [];
        while($startDate < $endDate) {
            if(\Schema::connection('mysql2')->hasTable('trafflow2_'.$startDate->format('Y-m-d'))) {
                $traff[] = \DB::connection('mysql2')->select('SELECT acc_index, SUM(trafsize) AS result FROM  ' . '`trafflow2_'
                    .$startDate->format('Y-m-d') . '` WHERE usr = 2198716 GROUP BY acc_index');
                foreach ($traff as $key => $day) {
                    foreach ($day as $device) {
                        $traffics[$device->acc_index] = isset($traffics[$device->acc_index]) ?
                            $traffics[$device->acc_index] + $device->result : $device->result;
                    }
                }
            }
            $startDate = $startDate->addDay();
        }
        return $traffics;
    }

    public function getTarifAttribute()
    {
        return \DB::connection('mysql2')->table('tarifs')->where('tarif_guid', $this->tarif_guid)->first();
    }

    public function getChangeTariffsAttribute()
    {
        $tariffs = explode('||', $this->tarif->followingtarifs);
        foreach ($tariffs as $tariff) {
            $return[] = \DB::connection('mysql2')->table('tarifs')->where('tarif_name', $tariff)->first();
        }
        return collect($return);
    }
}

resources/views/aero.blade.php
@extends('layouts.app')

@section('title')
    Авиарейсы
@endsection

@section('content')
    <div class="d-flex align-items-center justify-content-between">
        <h2>Расписание авиарейсов</h2>
    </div>
    <div class="row aero mb-4">
        <div class="col-12">
            <div class="block white mb-4">
                <div class="header">Аэропорт Тикси (IKS)</div>
                <div class="row contacts">
                    <div class="col-sm col-12 text-center">
                        <i class="icon phone"></i>
                        <a href="tel:+74116728337">8 (411) 672-83-37</a>
                    </div>
                    <div class="col-sm col-12 text-center">
                        <i class="icon map"></i>
                        <span>ул. Полярной Авиации, 4, Тикси, Респ. Саха (Якутия), 678400</span>
                    </div>
                    <div class="col-sm col-12 text-center">
                        <i class="icon mail"></i>
                        <a href="mailto:pal@tiksi.sakha.ru">pal@tiksi.sakha.ru</a>
                    </div>
                </div>
            </div>
        </div>
        @foreach ($planes as $key => $plane)
            <div class="col-12 mb-3">
                <div class="white plane">
                    <div class="row m-0 align-items-center flex-column flex-md-row">
                        <div class="col logo h-100">
                            <div class="d-flex text-md-left text-center align-items-center justify-content-center justify-content-md-start">
                                <div class="image"><img src="{{ Storage::url($plane->company->logotype) }}" class="img-fluid" alt=""></div>
                                <div class="info text-left">
                                    <div class="flight">{{ $plane->flight }}</div>
                                    <div class="title">{{ $plane->company->title }}</div>
                                </div>
                            </div>
                        </div>
                        <div class="col mb-3 mb-md-0 text-center text-md-center">
                            <div class="departure">{{ $plane->departure }}</div>
                            <span class="date">@if(now()->format('d.m.Y') == $plane->departure_at->format('d.m.Y')) Сегодня, {{ $plane->departure_at->format('H:i') }} @else {{ $plane->departure_at->isoFormat('Do MMMM, HH:mm') }}@endif</span>
                        </div>
                        <div class="col mb-3 mb-md-0 d-flex align-items-center justify-content-center lines">
                            <div class="air">
                                @include('include.plane', ['color' => $plane->status->color])
                            </div>
                            <span class="time">
                                {{ $plane->arrival_at->diffInHours($plane->departure_at) }}:@if($plane->arrival_at->subHours($plane->arrival_at->diffInHours($plane->departure_at))->diffInMinutes($plane->departure_at) == 0)00 @else{{ $plane->arrival_at->subHours($plane->arrival_at->diffInHours($plane->departure_at))->diffInMinutes($plane->departure_at) }} @endif</span>
                        </div>
                        <div class="col mb-2 mb-md-0 text-center">
                            <div class="arrival">{{ $plane->arrival }}</div>
                            <span class="date">@if(now()->format('d.m.Y') == $plane->arrival_at->format('d.m.Y')) Сегодня, {{ $plane->arrival_at->format('H:i') }} @else {{ $plane->arrival_at->isoFormat('Do MMMM, HH:mm') }}@endif</span>
                        </div>
                        <div class="col-md-2 col-12 mb-3 mb-md-0 text-md-right text-center"><span class="status" style="color: {{ $plane->status->color }}">{{ $plane->status->title }}</span></div>
                    </div>
                </div>
            </div>
        @endforeach
    </div>
@endsection

resources/views/afisha.blade.php
@extends('layouts.app')

@section('title')
    Киноафиша
@endsection

@section('content')
    <div class="d-flex align-items-center justify-content-between mb-5">
        <h2>Киноафиша</h2>
    </div>
    <div class="row afisha mb-4">
        @foreach ($films as $key => $film)
            @if($film->actual_sessions()->count())
                <div class="col-12 mb-9">
                    <div class="white">
                        <div class="d-flex top-content">
                            <div class="col-3 image">
                                <div class="d-block w-100 img">
                                    <div class="i" style="background-image: url('{{ Storage::url($film->image) }}')"></div>
                                </div>
                            </div>
                            <div class="about">
                                <div class="title">
                                    <h2>{{ $film->title }}</h2>
                                    @if($film->title_eng)<h3>{{ $film->title_eng }}</h3>@endif
                                </div>
                                <p class="description">
                                    {{ $film->description }}
                                </p>
                                {{-- <a href="#openDescription" class="btn btn-primary btn-sm mt-2 mb-3">Показать полностью</a> --}}
                                <div class="d-flex genre">
                                    <span>@if($film->duration){{ Carbon\CarbonInterval::minutes($film->duration)->cascade()->forHumans() }}@endif</span>
                                    <span>@if($film->genres)Жанр: {{ $film->genres->implode('title', ', ') }}@endif</span>
                                </div>
                            </div>
                        </div>
                        <div class="d-flex middle-content">
                            <ul class="nav days" id="pills-tab" role="tablist">
                                @foreach ($film->actual_sessions() as $day => $sessions)
                                    <li class="nav-item" role="presentation">
                                        <a
                                        class="nav-link @if($loop->first)active @endif"
                                        id="day{{ now()->setDateFrom($day)->format('d') }}-tab"
                                        data-toggle="pill" href="#film{{ $film->id }}day{{ now()->setDateFrom($day)->format('d') }}"
                                        role="tab"
                                        aria-controls="day{{ now()->setDateFrom($day)->format('d') }}"
                                        aria-selected="true"
                                        >
                                            <span class="day">{{ mb_convert_case(now()->setDateFrom($day)->translatedFormat('l'), MB_CASE_TITLE, "UTF-8")  }}</span>
                                            <span class="number">{{ now()->setDateFrom($day)->translatedFormat('j')  }} {{now()->setDateFrom($day)->getTranslatedMonthName('Do MMMM')}}</span>
                                        </a>
                                    </li>
                                @endforeach
                            </ul>
                        </div>
                        <div class="d-flex bottom-content">
                            <div class="tab-content" id="pills-tabContent">
                                @foreach ($film->actual_sessions() as $day => $sessions)
                                    @php
                                        $active = false;
                                    @endphp
                                    <div class="tab-pane fade @if($loop->first)show active @endif" id="film{{ $film->id }}day{{ now()->setDateFrom($day)->format('d') }}" role="tabpanel" aria-labelledby="day{{ now()->setDateFrom($day)->format('d') }}-tab">
                                        <ul>
                                            @foreach ($sessions as $key => $session)
                                                @if($loop->parent->first)
                                                    <li class="@if($session->display_at < now()) disabled @elseif(!$active) @php $active = true; @endphp active @endif" >{{ $session->display_at->format('H:i') }}</li>
                                                @else
                                                    <li>{{ $session->display_at->format('H:i') }}</li>
                                                @endif
                                            @endforeach
                                        </ul>
                                    </div>
                                @endforeach
                            </div>
                        </div>
                    </div>
                </div>
            @endif
        @endforeach
    </div>
@endsection

resources/views/closed.blade.php
@extends('layouts.closed')

@section('title')
    Страница входа
@endsection

@section('content')
    <div class="row">
        <div class="col-12 h-100">
            <h1>Добро пожаловать в сеть</h1>
            <h2>«Единый булун»</h2>
            <div class="vhod">
                <input type="text" placeholder="Фамилия">
                <input type="text" placeholder="Имя">
                <input type="text" placeholder="Отчество">
                <input type="text" class="phone" placeholder="Номер телефона">
                <div class="d-flex">
                    <input type = "checkbox" id="oferta">
                    <label for = "oferta">Я принимаю условия договора оферты</label>
                </div>
                <button class="button small">ЗАРЕГИСТРИРОВАТЬСЯ</button>
            </div>
        </div>
    </div>
@endsection

resources/views/index.blade.php
@extends('layouts.app')

@section('title')
    Главная страница
@endsection

@section('content')
    <div class="row mb-2">
        <div class="col-md-4 col-12 order-md-0 order-1">
            <div class="block d-flex flex-column full white mb-4">
                <div class="header text-center">
                    Новости района
                </div>
                <div class="d-flex flex-grow-1 flex-column">
                    @foreach ($newses_bulunsk as $key => $news)
                        <div class="news flex-grow-1 d-flex align-items-center justify-content-start py-0 px-3">
                            <a href="{{ route('news.news', ['id' => $news->id]) }}">{{ $news->title }}</a>
                        </div>
                    @endforeach
                </div>
                <div class="all"><a href="{{ route('news.index') }}">ВСЕ НОВОСТИ</a></div>
            </div>
        </div>
        <div class="col-md-8 col-12 order-md-1 order-0">
            <div class="row">
                @foreach ($newses as $key => $news)
                    @if($loop->first)
                        <div class="col-12 mb-4">
                            <div class="news big white">
                                <div class="top" style="background-image: url('{{ Storage::url($news->image_url) }}')">
                                    <div class="content">
                                        <div class="text">
                                            <span class="category {{ $news->category->color->eng }}">{{ $news->category->title }}</span>
                                            <h3><a href="{{ route('news.news', ['id' => $news->id]) }}">{{ $news->title }}</a></h3>
                                        </div>
                                    </div>
                                    <a href="#" class="share"></a>
                                </div>
                                <div class="bottom justify-content-between align-items-center">
                                    <span>{{ $news->created_at->format('d.m.Y H:i') }}</span>
                                    <span class="d-flex align-items-center">
                                        <i class="icon read"></i>{{ $news->reads }} <i class="icon comments ml-4"></i>0
                                    </span>
                                    <span>Андрей Иванов</span>
                                </div>
                            </div>
                        </div>
                    @else
                        <div class="col-sm-6 col-12 mb-4">
                            <div class="news white">
                                <div class="top" style="background-image: url('{{ Storage::url($news->image_url) }}')">
                                    <div class="content">
                                        <div class="text">
                                            <span class="category {{ $news->category->color->eng }}">{{ $news->category->title }}</span>
                                            <h3><a href="{{ route('news.news', ['id' => $news->id]) }}">{{ $news->title }}</a></h3>
                                        </div>
                                    </div>
                                    <a href="#" class="share"></a>
                                </div>
                                <div class="bottom justify-content-between align-items-center">
                                    <span>{{ $news->created_at->format('d.m.Y H:i') }}</span>
                                    <span class="d-flex align-items-center">
                                        <i class="icon comments"></i>0
                                    </span>
                                </div>
                            </div>
                        </div>
                    @endif
                @endforeach
            </div>
        </div>
    </div>
    <div class="row mb-5">
        <div class="col-12">
            <div class="white block forum">
                <div class="header d-flex justify-content-between align-items-center">
                    <span class="title">Обсуждаемые темы</span>
                    <a href="{{ route('forum.add') }}" class="create">Создать тему</a>
                </div>
                <div class="body">
                    <div class="row p-3 m-0">
                        @foreach ($topics as $key => $topic)
                            <div class="col-lg-4 col-md-6 col-12 my-3">
                                <div class="topic p-0">
                                    <div class="image">
                                        @if($topic->last)
                                            <img src="@if($topic->last->user && $topic->last->user->photo){{ Storage::url($topic->last->user->photo) }}@else{{ asset('images/noavatar.jpg') }}@endif" alt="">
                                        @else
                                            <img src="@if($topic->user && $topic->user->photo){{ Storage::url($topic->user->photo) }}@else{{ asset('images/noavatar.jpg') }}@endif" alt="">
                                        @endif
                                    </div>
                                    <div class="column">
                                        <h4 class="title"><a href="{{ route('forum.topic', ['id' => $topic->id]) }}">{{ $topic->title }}</a></h4>
                                        <span class="time">@if($topic->last){{ $topic->last->created_at->diffForHumans() }}@else{{ $topic->created_at->diffForHumans() }}@endif</span>
                                    </div>
                                </div>
                            </div>
                        @endforeach
                    </div>
                </div>
                <div class="all"><a href="{{ route('forum.index') }}">ВСЕ ТЕМЫ</a></div>
            </div>
        </div>
    </div>
    <div class="row mb-4">
        <div class="col-12 mb-3">
            <div class="d-flex justify-content-between align-items-center">
                <h3>Киноафиша</h3>
                <a href="{{ route('afisha') }}">Все фильмы</a>
            </div>
        </div>
        <div class="col-12">
            <div class="row afisha">
                @foreach ($films as $key => $film)
                    <div class="col-sm col-12 film mb-4">
                        <div class="image" style="background-image: url('{{ Storage::url($film->image) }}')"></div>
                        <h4 class="title">{{ $film->title }}</h4>
                        <span class="time">{{ Carbon\CarbonInterval::minutes($film->duration)->cascade()->forHumans() }}</span>
                    </div>
                @endforeach
            </div>
        </div>
    </div>
    <div class="row mb-5">
        <div class="col-12 mb-3">
            <div class="d-flex justify-content-between align-items-center">
                <h3>Объявления</h3>
                <a href="{{ route('ads.index') }}">Все объявления</a>
            </div>
        </div>
        <div class="col-12">
            <div class="row ads">
                @foreach ($ads as $key => $ad)
                    <div class="col-sm col-12 ">
                        <div class="ad white">
                            <div class="image" style="
                            @foreach ($ad->photos as $key => $photo)
                            @if($loop->first)
                            background-image: url('{{ Storage::url($photo->url) }}')
                            @endif
                            @endforeach
                            "></div>
                            <div class="content">
                                <h4 class="title">{{ $ad->title }}</h4>
                                <span class="price">{{ number_format($ad->price, 0, '.', ' ') }}₽</span>
                                <p>
                                    {{ Str::limit($ad->text, 100, '...') }}
                                </p>
                            </div>
                        </div>
                    </div>
                @endforeach
            </div>
        </div>
    </div>
@endsection