routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'PageController@index')->name('index');

//Новости
Route::group(['namespace' => 'News', 'as' => 'news.', 'prefix' => 'news'], function() {
    Route::get('/', 'NewsController@index')->name('index');
    Route::get('section/{id}', 'NewsController@section')->name('section');
    Route::post('add', 'NewsController@create')->name('create');
    Route::post('test', 'NewsController@test')->name('test');
    Route::put('update/{id}', 'NewsController@update')->name('update');
    Route::get('{id}', 'NewsController@news')->name('news');
});

//Объявления
Route::group(['namespace' => 'Ad', 'as' => 'ads.', 'prefix' => 'ads'], function() {
    Route::get('/', 'AdController@index')->name('index');
    Route::get('add', 'AdController@add')->name('add');
    Route::post('add', 'AdController@create')->name('create');
    Route::put('edit/{id}', 'AdController@update')->name('update');
    Route::get('category/{category_id}', 'AdController@category')->name('category');
    Route::get('ad/{id}', 'AdController@ad')->name('ad');
});

// Мероприятния
Route::group(['namespace' => 'Event', 'as' => 'events.', 'prefix' => 'events'], function() {
    Route::get('/', 'EventController@index')->name('index');
    Route::get('section/{section_id}', 'EventController@section')->name('section');
    Route::get('event/{id}', 'EventController@event')->name('event');
});

//Форум
Route::group(['as' => 'forum.', 'prefix' => 'forum', 'namespace' => 'Forum'], function() {
    Route::get('/', 'TopicController@index')->name('index');
    Route::get('add', 'TopicController@add')->name('add');
    Route::post('add', 'TopicController@create')->name('create');
    Route::get('topic/{id}', 'TopicController@topic')->name('topic');
    Route::post('topic/{id}', 'TopicController@create_message')->name('create_message');
});

Route::get('road', 'PageController@road')->name('road');
Route::get('bus', 'PageController@bus')->name('bus');
Route::get('weather', 'PageController@weather')->name('weather');
Route::get('aero', 'PageController@aero')->name('aero');
Route::get('afisha', 'PageController@afisha')->name('afisha');

//Администрация
Route::group(['as' => 'administration.', 'prefix' => 'administration'], function() {
    Route::get('/', 'AdministrationController@index')->name('index');
    Route::get('complaint', 'AdministrationController@complaint')->name('complaint');
    Route::post('complaint', 'AbuseFormController@mail_to_administration')->name('mail_to_administration');
    Route::group(['prefix' => 'measure', 'as' => 'measure.'], function() {
        Route::get('/', 'AdministrationController@measures')->name('index');
        Route::get('show/{id}', 'AdministrationController@measure')->name('show');
    });
});

//Архив
Route::group(['as' => 'archive.', 'prefix' => 'archive'], function() {
    Route::get('/', 'ArchiveController@index')->name('index');
    Route::get('upload', 'ArchiveController@upload')->name('upload.file');
    Route::get('mayak', 'ArchiveController@mayak')->name('mayak');
    Route::get('mayak/{id}', 'ArchiveController@show_mayak')->name('show_mayak');
    Route::get('add', 'ArchiveController@add')->name('add');
    Route::post('add', 'ArchiveController@create')->name('create');
    Route::get('section/{id}', 'ArchiveController@section')->name('section');
});

//Лк
Route::group(['prefix' => 'lk', 'as' => 'lk.', 'middleware' => 'auth'], function() {
    Route::get('/', 'UserController@index')->name('index');
    Route::put('/', 'UserController@update')->name('update');
    Route::get('news', 'UserController@news')->name('news');
    Route::get('ads', 'UserController@ads')->name('ads');
    Route::get('events', 'UserController@events')->name('events');
    Route::get('balance', 'UserController@balance')->name('balance');
    Route::get('traffic_info', 'UserController@traffic_info')->name('traffic_info');
    Route::get('tariff', 'UserController@tariff')->name('tariff');
    Route::post('tariff', 'UserController@change_tariff')->name('change_tariff');
    Route::get('documents', 'UserController@documents')->name('documents');
    Route::post('yandex_pay', 'UserController@yandex_pay')->name('yandex_pay');
});


Route::post('ckeditor/image_upload', 'CKEditorController@upload')->name('upload.image');
Route::get('download/{id}', 'PageController@download_file')->name('download_file');

Route::group(['prefix' => 'comment', 'as' => 'comment.'], function() {
    Route::post('add', 'CommentController@create')->name('create');
});

//Админка
Route::group(['prefix' => 'admin', 'as' => 'admin.'], function(){
    Route::get('/', 'AdminController@index')->name('index');

    Route::group(['namespace' => 'Admin'], function() {
        //Новости
        Route::group(['prefix' => 'news', 'as' => 'news.'], function() {
            Route::get('all', 'NewsController@all')->name('all');
            Route::get('/', 'NewsController@new')->name('new');
            Route::get('edit/{id}', 'NewsController@edit')->name('edit');
            Route::delete('{id}', 'NewsController@delete')->name('delete');
            //Категории новостей
            Route::group(['prefix' => 'category', 'as' => 'category.'], function(){
                Route::get('/', 'NewsController@all_categories')->name('all');
                Route::post('/', 'NewsController@create_category')->name('create');
                Route::get('{id}', 'NewsController@edit_category')->name('edit');
                Route::put('{id}', 'NewsController@update_category')->name('update');
                Route::delete('{id}', 'NewsController@delete_category')->name('delete');
            });
            //Теги новостей
            Route::group(['prefix' => 'tags', 'as' => 'tags.'], function(){
                Route::get('/', 'NewsController@all_tags')->name('all');
                Route::post('new', 'NewsController@create_tag')->name('create');
                Route::delete('{id}', 'NewsController@delete_tag')->name('delete');
            });
            //Секции новостей
            Route::group(['prefix' => 'sections', 'as' => 'sections.'], function(){
                Route::get('/', 'NewsController@all_sections')->name('all');
                Route::post('new', 'NewsController@create_section')->name('create');
                Route::delete('{id}', 'NewsController@delete_section')->name('delete');
            });
        });

        //Объявления
        Route::group(['prefix' => 'ads', 'as' => 'ads.'], function(){
            Route::get('all', 'AdsController@all')->name('all');
            Route::get('/', 'AdsController@new')->name('new');
            Route::get('edit/{id}', 'AdsController@edit')->name('edit');
            Route::delete('{id}', 'AdsController@delete')->name('delete');
            //Категории объявлений
            Route::group(['prefix' => 'categories', 'as' => 'categories.'], function(){
                Route::get('/', 'AdsController@all_categories')->name('all');
                Route::post('/', 'AdsController@create_category')->name('create');
                Route::delete('{id}', 'AdsController@delete_category')->name('delete');
            });
            //Города объявлений
            Route::group(['prefix' => 'cities', 'as' => 'cities.'], function(){
                Route::get('/', 'AdsController@all_cities')->name('all');
                Route::post('new', 'AdsController@create_city')->name('create');
                Route::delete('{id}', 'AdsController@delete_city')->name('delete');
            });
        });

        //Мероприятия
        Route::group(['prefix' => 'events', 'as' => 'events.'], function(){
            Route::get('all', 'EventsController@all')->name('all');
            Route::get('/', 'EventsController@new')->name('new');
            Route::post('/', 'EventsController@create')->name('create');
            Route::get('edit/{id}', 'EventsController@edit')->name('edit');
            Route::put('edit/{id}', 'EventsController@update')->name('update');
            Route::delete('{id}', 'EventsController@delete')->name('delete');

            //Категории мероприятий
            Route::group(['prefix' => 'categories', 'as' => 'categories.'], function(){
                Route::get('/', 'EventsController@all_categories')->name('all');
                Route::post('/', 'EventsController@create_category')->name('create');
                Route::get('{id}', 'EventsController@edit_category')->name('edit');
                Route::put('{id}', 'EventsController@update_category')->name('update');
                Route::delete('{id}', 'EventsController@delete_category')->name('delete');
            });

            //Секции новостей
            Route::group(['prefix' => 'sections', 'as' => 'sections.'], function(){
                Route::get('/', 'EventsController@all_sections')->name('all');
                Route::post('new', 'EventsController@create_section')->name('create');
                Route::delete('{id}', 'EventsController@delete_section')->name('delete');
            });
        });

        //Пользователи
        Route::group(['prefix' => 'users', 'as' => 'users.'], function() {
            Route::get('/', 'UsersController@all')->name('all');
            Route::get('edit/{id}', 'UsersController@edit')->name('edit');
            Route::put('edit/{id}', 'UsersController@update')->name('update');
            Route::delete('delete/{id}', 'UsersController@delete')->name('delete');
        });

        //Группы
        Route::group(['prefix' => 'groups', 'as' => 'groups.'], function() {

app/Ad.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Ad extends Model
{
    protected $fillable = [
        'title', 'city_id', 'category_id', 'price', 'text', 'addres', 'phone', 'user_id'
    ];

    public function comments()
    {
        return $this->morphMany('App\Comment', 'commentable');
    }

    public function likes()
    {
        return $this->morphMany('App\Like', 'liketable');
    }

    public function city()
    {
        return $this->belongsTo(City::class);
    }

    public function category()
    {
        return $this->belongsTo(AdCategory::class, 'category_id');
    }

    public function photos()
    {
        return $this->hasMany(AdPhoto::class);
    }

    public function user()
    {
        return $this->belongsTo(User::class, 'user_id', 'shortguid');
    }
}

app/Http/Controllers/Ad/AdCategoryController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class AdCategoryController extends Controller
{
    //
}

app/Http/Controllers/Ad/AdController.php
<?php

namespace App\Http\Controllers\Ad;

use App\Http\Controllers\Controller;
use App\AdCategory;
use App\AdPhoto;
use Illuminate\Http\Request;

class AdController extends Controller
{
    public function index()
    {
        $categories = \App\AdCategory::all();
        return view('ads.index', compact('categories'));
    }

    public function category($category_id)
    {
        $category = \App\AdCategory::find($category_id);
        $ads = \App\Ad::where('category_id', $category_id)->orderBy('created_at', 'desc')->paginate(10);
        return view('ads.category', compact('ads', 'category'));
    }

    public function ad($id)
    {
        $ad = \App\Ad::find($id);
        $ad->increment('reads');
        $like = \App\Like::hasLike($ad);
        return view('ads.ad', compact('ad', 'like'));
    }

    public function add()
    {
        $categories = \App\AdCategory::all();
        return view('ads.new', compact('categories'));
    }

    public function create(Request $request)
    {
        $request->validate([
            'title' => 'required',
            'category_id' => 'required',
            'city_id' => 'required',
            'price' => 'min:0'
        ]);
        $ad = \App\Ad::create($request->all() + ['user_id' => \Auth::user()->id]);
        if($request->has('images')) {
            foreach ($request->images as $key => $image) {
                $url = \Storage::disk('public')->putFile('images', $image);
                \App\AdPhoto::create([
                    'url' => $url,
                    'ad_id' => $ad->id
                ]);
            }
        }
        return redirect(route('ads.index'))->with('success', 'Объявление успешно добавлено');
    }

    public function update(Request $request, $id)
    {
        $ad = \App\Ad::find($id);
        if($request->has('images')) {
            foreach ($ad->photos as $key => $photo) {
                \Storage::disk('public')->delete($photo->url);
                $photo->delete();
            }
            foreach ($request->images as $key => $image) {
                $url = \Storage::disk('public')->putFile('images', $image);
                \App\AdPhoto::create([
                    'url' => $url,
                    'ad_id' => $ad->id
                ]);
            }
        }
        $ad->update($request->all());
        return redirect(route('ads.index'))->with('success', 'Объявление успешно обновлено!');
    }
}

app/Http/Controllers/Admin/AdsController.php
<?php

namespace App\Http\Controllers\Admin;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class AdsController extends Controller
{
    public function all()
    {
        $ads = \App\Ad::paginate(20);
        return view('admin.ads.all', compact('ads'));
    }

    public function new()
    {
        $categories = \App\AdCategory::all();
        $cities = \App\City::all();
        return view('admin.ads.new', compact('categories', 'cities'));
    }

    public function edit($id)
    {
        $categories = \App\AdCategory::all();
        $cities = \App\City::all();
        $ad = \App\Ad::find($id);
        return view('admin.ads.edit', compact('categories', 'cities', 'ad'));
    }

    public function delete($id)
    {
        $ad = \App\Ad::find($id);
        foreach ($ad->photos as $key => $photo) {
            \Storage::disk('public')->delete($photo->url);
            $photo->delete();
        }
        $ad->delete();
        return redirect(route('admin.ads.all'))->with('success', 'Объявление успешно удалено');
    }

    public function all_categories()
    {
        $categories = \App\AdCategory::all();
        return view('admin.ads.categories', compact('categories'));
    }

    public function create_category(Request $request)
    {
        $request->validate([
            'title' => 'required|unique:ad_categories',
        ]);
        $category = \App\AdCategory::create($request->all());
        if(!$category) {
            return redirect(route('admin.ads.categories.all'))->with('error', 'При добавлении категории <strong>'.$request->title.'</strong> произошла ошибка');
        } else {
            return redirect(route('admin.ads.categories.all'))->with('success', 'Категория <strong>'.$category->title.'</strong> успешно добавлена');
        }
    }

    public function delete_category(Request $request, $id)
    {
        $category = \App\AdCategory::find($id);
        $title = $category->title;
        $category->ads()->delete();
        $category->delete();
        return redirect(route('admin.ads.category.all'))->with('success', 'Категория <strong>'.$title.'</strong> успешно удалена');
    }

    public function all_cities()
    {
        $cities = \App\City::all();
        return view('admin.ads.cities', compact('cities'));
    }

    public function create_city(Request $request)
    {
        $request->validate([
            'title' => 'required|unique:cities',
        ]);
        $city = \App\City::create($request->all());
        if(!$city) {
            return redirect(route('admin.ads.cities.all'))->with('error', 'При добавлении города <strong>'.$request->title.'</strong> произошла ошибка');
        } else {
            return redirect(route('admin.ads.cities.all'))->with('success', 'Город <strong>'.$city->title.'</strong> успешно добавлен');
        }
    }

    public function delete_city(Request $request, $id)
    {
        $city = \App\City::find($id);
        $title = $city->title;
        $city->ads()->delete();
        $city->delete();
        return redirect(route('admin.ads.cities.all'))->with('success', 'Город <strong>'.$title.'</strong> успешно удален');
    }
}

resources/views/admin/ads/all.blade.php
@extends('layouts.admin')

@section('title')
    Все объявления - АдминПанель - Булунский портал
@endsection

@section('content')
    <div class="table-responsive">
        <table class="table table-sm">
            <thead class="thead-dark">
                <tr>
                    <th scope="col">#</th>
                    <th scope="col">Город</th>
                    <th scope="col">Товар</th>
                    <th scope="col">Категория</th>
                    <th scope="col">Цена</th>
                    <th scope="col">Описание</th>
                    <th scope="col">Дата публикации</th>
                    <th scope="col"></th>
                </tr>
            </thead>
            <tbody>
                @if($ads->count() != 0)
                    @foreach ($ads as $key => $ad)
                        <tr>
                            <td scope="col" class="align-middle">{{$ad->id}}</td>
                            <td class="align-middle">{{$ad->city->title}}</td>
                            <td class="align-middle">{{$ad->title}}</td>
                            <td class="align-middle">{{$ad->category->title}}</td>
                            <td class="align-middle">{{$ad->price}}</td>
                            <td class="align-middle">{{Str::limit($ad->text, 300, '...')}}</td>
                            <td class="align-middle">{{$ad->created_at->format('d.m.Y в H:i')}}</td>
                            <td class="align-middle text-right">
                                <div class="d-flex justify-content-end">
                                    <a href="{{route('admin.ads.edit', ['id' => $ad->id])}}" role="button" class="btn btn-sm btn-success"><span class="oi oi-pencil"></span></a>
                                    <form action="{{route('admin.ads.delete', ['id' => $ad->id])}}" method="post">
                                        @csrf
                                        @method('delete')
                                        <button type="sumbit" class="btn btn-danger btn-sm ml-2" onclick="return confirm('Удалить новости {{$ad->title}}?');">
                                            <span class="oi oi-trash"></span>
                                        </button>
                                    </form>
                                </div>
                            </td>
                        </tr>
                    @endforeach
                @else
                    <tr>
                        <td colspan="8">Объявлений нет</td>
                    </tr>
                @endif
            </tbody>
        </table>
        {{$ads->links()}}
    </div>
@endsection

resources/views/admin/ads/categories.blade.php
@extends('layouts.admin')

@section('title')
    Категории - Объявления - АндминПанель - Булунский портал
@endsection

@section('content')
    <div class="table-responsive">
        <table class="table table-sm">
            <thead class="thead-dark">
                <th>#</th>
                <th>Название</th>
                <th>Объявлений в категории</th>
                <th></th>
            </thead>
            <tbody>
                @foreach ($categories as $key => $category)
                    <tr>
                        <td class="align-middle">{{$category->id}}</td>
                        <td class="align-middle">{{$category->title}}</td>
                        <td class="align-middle">{{$category->ads->count()}}</td>
                        <td class="align-middle text-right">
                            <form action="{{route('admin.ads.categories.delete', ['id' => $category->id])}}" method="post">
                                @csrf
                                @method('delete')
                                <button type="sumbit" class="btn btn-danger btn-sm" onclick="return confirm('Удалить категорию {{$category->title}}? Это удалит и {{$category->ads->count()}} новостей.');">
                                    <span class="oi oi-trash"></span>
                                </button>
                            </form>
                        </td>
                    </tr>
                @endforeach
                <tr>
                    <td colspan="4" class="p-2">
                        <form action="{{route('admin.ads.categories.create')}}" method="post">
                            @csrf
                            <div class="form-group row">
                                <label for="inputPassword" class="col-sm-1 col-form-label">Название</label>
                                <div class="col-sm-2">
                                    <input type="text" name="title" class="form-control">
                                </div>
                                <div class="col-sm-2">
                                    <button type="submit" name="button" class="btn btn-primary">Создать</button>
                                </div>
                            </div>
                        </form>
                    </td>
                </tr>
            </tbody>
        </table>
    </div>
@endsection

resources/views/admin/ads/cities.blade.php
@extends('layouts.admin')

@section('title')
    Города - Объявления - АндминПанель - Булунский портал
@endsection

@section('content')
    <div class="table-responsive">
        <table class="table table-sm">
            <thead class="thead-dark">
                <th>#</th>
                <th>Название</th>
                <th>Объявлений в городе</th>
                <th></th>
            </thead>
            <tbody>
                @foreach ($cities as $key => $city)
                    <tr>
                        <td class="align-middle">{{$city->id}}</td>
                        <td class="align-middle">{{$city->title}}</td>
                        <td class="align-middle">{{$city->ads->count()}}</td>
                        <td class="align-middle text-right">
                            <form action="{{route('admin.ads.cities.delete', ['id' => $city->id])}}" method="post">
                                @csrf
                                @method('delete')
                                <button type="sumbit" class="btn btn-danger btn-sm" onclick="return confirm('Удалить город {{$city->title}}? Это удалит и {{$city->ads->count()}} объявлений.');">
                                    <span class="oi oi-trash"></span>
                                </button>
                            </form>
                        </td>
                    </tr>
                @endforeach
                <tr>
                    <td colspan="4" class="p-2">
                        <form action="{{route('admin.ads.cities.create')}}" method="post">
                            @csrf
                            <div class="form-group row">
                                <label for="inputPassword" class="col-sm-1 col-form-label">Название</label>
                                <div class="col-sm-2">
                                    <input type="text" name="title" class="form-control">
                                </div>
                                <div class="col-sm-2">
                                    <button type="submit" name="button" class="btn btn-primary">Создать</button>
                                </div>
                            </div>
                        </form>
                    </td>
                </tr>
            </tbody>
        </table>
    </div>
@endsection

resources/views/admin/ads/edit.blade.php
@extends('layouts.admin')

@section('title')
    Редактирование объявления - АдминПанель - Булунский Портал
@endsection

@section('content')
    <div class="container my-2">
        <div class="col-12">
            <form action="{{route('ads.update', ['id' => $ad->id])}}" method="post" enctype="multipart/form-data">
                @csrf
                @method('put')
                <div class="form-group">
                    <label>Заголовок</label>
                    <input type="text" name="title" class="form-control" placeholder="Введите заголовок" value="{{ $ad->title }}" required>
                </div>
                <div class="form-group">
                    <label>Город</label>
                    <select name="city_id" class="form-control dropdown" required>
                        @foreach ($cities as $key => $city)
                            <option value="{{$city->id}}" @if($ad->city_id == $city->id) selected @endif>{{$city->title}}</option>
                        @endforeach
                    </select>
                </div>
                <div class="form-group">
                    <label>Категория</label>
                    <select name="category_id" class="form-control dropdown" required>
                        @foreach ($categories as $key => $category)
                            <option value="{{$category->id}}" @if($ad->category_id == $category->id) selected @endif>{{$category->title}}</option>
                        @endforeach
                    </select>
                </div>
                <label>Изображения</label>
                @foreach ($ad->photos as $key => $photo)
                    <img src="{{ Storage::url($photo->url) }}" style="max-width: 200px;" alt="">
                @endforeach
                <div class="custom-file mb-3 form-group">
                    <input type="file" name="images[]" class="custom-file-input" id="customFileLangHTML" multiple>
                    <label class="custom-file-label" for="customFileLangHTML" data-browse="Выбрать">Изображения</label>
                </div>
                <div class="form-group">
                    <label>Описание</label>
                    <textarea name="text" class="form-control" required>{{ $ad->text }}</textarea>
                </div>
                <div class="form-group">
                    <label>Цена</label>
                    <input type="number" name="price" min-value="0" step="1" class="form-control" value="{{ $ad->price }}" required>
                </div>
                <div class="form-group">
                    <label>Адрес</label>
                    <input type="text" name="addres" class="form-control" placeholder="ул. Шевченко, д.15" required value="{{ $ad->addres }}">
                </div>
                <div class="form-group">
                    <label>Телефон</label>
                    <input type="text" name="phone" class="form-control phone" required value="{{ $ad->phone }}">
                </div>
                <button type="submit" class="btn btn-primary">Обновить</button>
            </form>
        </div>
    </div>
@endsection

resources/views/admin/ads/new.blade.php
@extends('layouts.admin')

@section('title')
    Добавление объявление - АдминПанель - Булунский Портал
@endsection

@section('content')
    <div class="container my-2">
        <div class="col-12">
            <form action="{{route('ads.create')}}" method="post" enctype="multipart/form-data">
                @csrf
                <div class="form-group">
                    <label>Заголовок</label>
                    <input type="text" name="title" class="form-control" placeholder="Введите заголовок" required>
                </div>
                <div class="form-group">
                    <label>Город</label>
                    <select name="city_id" class="form-control dropdown" id="city" required>
                        @foreach ($cities as $key => $city)
                            <option value="{{$city->id}}">{{$city->title}}</option>
                        @endforeach
                    </select>
                </div>
                <div class="form-group">
                    <label>Категория</label>
                    <select name="category_id" class="form-control dropdown" required>
                        @foreach ($categories as $key => $category)
                            <option value="{{$category->id}}">{{$category->title}}</option>
                        @endforeach
                    </select>
                </div>
                <label>Изображения</label>
                <div class="custom-file mb-3 form-group">
                    <input type="file" name="images[]" class="custom-file-input" id="customFileLangHTML" multiple required>
                    <label class="custom-file-label" for="customFileLangHTML" data-browse="Выбрать">Изображения</label>
                </div>
                <div class="form-group">
                    <label>Описание</label>
                    <textarea name="text" class="form-control" placeholder="Описание товара" required></textarea>
                </div>
                <div class="form-group">
                    <label>Цена</label>
                    <input type="number" name="price" min-value="0" step="1" class="form-control" placeholder="500" required>
                </div>
                <div class="form-group">
                    <label>Адрес</label>
                    <input type="text" name="addres" class="form-control" placeholder="ул. Шевченко, д.15" required>
                </div>
                <div class="form-group">
                    <label>Телефон</label>
                    <input type="text" name="phone" class="form-control phone" required>
                </div>
                <button type="submit" class="btn btn-primary">Добавить</button>
            </form>
        </div>
    </div>
@endsection