routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'PageController@index')->name('index');

//Новости
Route::group(['namespace' => 'News', 'as' => 'news.', 'prefix' => 'news'], function() {
    Route::get('/', 'NewsController@index')->name('index');
    Route::get('section/{id}', 'NewsController@section')->name('section');
    Route::post('add', 'NewsController@create')->name('create');
    Route::post('test', 'NewsController@test')->name('test');
    Route::put('update/{id}', 'NewsController@update')->name('update');
    Route::get('{id}', 'NewsController@news')->name('news');
});

//Объявления
Route::group(['namespace' => 'Ad', 'as' => 'ads.', 'prefix' => 'ads'], function() {
    Route::get('/', 'AdController@index')->name('index');
    Route::get('add', 'AdController@add')->name('add');
    Route::post('add', 'AdController@create')->name('create');
    Route::put('edit/{id}', 'AdController@update')->name('update');
    Route::get('category/{category_id}', 'AdController@category')->name('category');
    Route::get('ad/{id}', 'AdController@ad')->name('ad');
});

// Мероприятния
Route::group(['namespace' => 'Event', 'as' => 'events.', 'prefix' => 'events'], function() {
    Route::get('/', 'EventController@index')->name('index');
    Route::get('section/{section_id}', 'EventController@section')->name('section');
    Route::get('event/{id}', 'EventController@event')->name('event');
});

//Форум
Route::group(['as' => 'forum.', 'prefix' => 'forum', 'namespace' => 'Forum'], function() {
    Route::get('/', 'TopicController@index')->name('index');
    Route::get('add', 'TopicController@add')->name('add');
    Route::post('add', 'TopicController@create')->name('create');
    Route::get('topic/{id}', 'TopicController@topic')->name('topic');
    Route::post('topic/{id}', 'TopicController@create_message')->name('create_message');
});

Route::get('road', 'PageController@road')->name('road');
Route::get('bus', 'PageController@bus')->name('bus');
Route::get('weather', 'PageController@weather')->name('weather');
Route::get('aero', 'PageController@aero')->name('aero');
Route::get('afisha', 'PageController@afisha')->name('afisha');

//Администрация
Route::group(['as' => 'administration.', 'prefix' => 'administration'], function() {
    Route::get('/', 'AdministrationController@index')->name('index');
    Route::get('complaint', 'AdministrationController@complaint')->name('complaint');
    Route::post('complaint', 'AbuseFormController@mail_to_administration')->name('mail_to_administration');
    Route::group(['prefix' => 'measure', 'as' => 'measure.'], function() {
        Route::get('/', 'AdministrationController@measures')->name('index');
        Route::get('show/{id}', 'AdministrationController@measure')->name('show');
    });
});

//Архив
Route::group(['as' => 'archive.', 'prefix' => 'archive'], function() {
    Route::get('/', 'ArchiveController@index')->name('index');
    Route::get('upload', 'ArchiveController@upload')->name('upload.file');
    Route::get('mayak', 'ArchiveController@mayak')->name('mayak');
    Route::get('mayak/{id}', 'ArchiveController@show_mayak')->name('show_mayak');
    Route::get('add', 'ArchiveController@add')->name('add');
    Route::post('add', 'ArchiveController@create')->name('create');
    Route::get('section/{id}', 'ArchiveController@section')->name('section');
});

//Лк
Route::group(['prefix' => 'lk', 'as' => 'lk.', 'middleware' => 'auth'], function() {
    Route::get('/', 'UserController@index')->name('index');
    Route::put('/', 'UserController@update')->name('update');
    Route::get('news', 'UserController@news')->name('news');
    Route::get('ads', 'UserController@ads')->name('ads');
    Route::get('events', 'UserController@events')->name('events');
    Route::get('balance', 'UserController@balance')->name('balance');
    Route::get('traffic_info', 'UserController@traffic_info')->name('traffic_info');
    Route::get('tariff', 'UserController@tariff')->name('tariff');
    Route::post('tariff', 'UserController@change_tariff')->name('change_tariff');
    Route::get('documents', 'UserController@documents')->name('documents');
    Route::post('yandex_pay', 'UserController@yandex_pay')->name('yandex_pay');
});


Route::post('ckeditor/image_upload', 'CKEditorController@upload')->name('upload.image');
Route::get('download/{id}', 'PageController@download_file')->name('download_file');

Route::group(['prefix' => 'comment', 'as' => 'comment.'], function() {
    Route::post('add', 'CommentController@create')->name('create');
});

//Админка
Route::group(['prefix' => 'admin', 'as' => 'admin.'], function(){
    Route::get('/', 'AdminController@index')->name('index');

    Route::group(['namespace' => 'Admin'], function() {
        //Новости
        Route::group(['prefix' => 'news', 'as' => 'news.'], function() {
            Route::get('all', 'NewsController@all')->name('all');
            Route::get('/', 'NewsController@new')->name('new');
            Route::get('edit/{id}', 'NewsController@edit')->name('edit');
            Route::delete('{id}', 'NewsController@delete')->name('delete');
            //Категории новостей
            Route::group(['prefix' => 'category', 'as' => 'category.'], function(){
                Route::get('/', 'NewsController@all_categories')->name('all');
                Route::post('/', 'NewsController@create_category')->name('create');
                Route::get('{id}', 'NewsController@edit_category')->name('edit');
                Route::put('{id}', 'NewsController@update_category')->name('update');
                Route::delete('{id}', 'NewsController@delete_category')->name('delete');
            });
            //Теги новостей
            Route::group(['prefix' => 'tags', 'as' => 'tags.'], function(){
                Route::get('/', 'NewsController@all_tags')->name('all');
                Route::post('new', 'NewsController@create_tag')->name('create');
                Route::delete('{id}', 'NewsController@delete_tag')->name('delete');
            });
            //Секции новостей
            Route::group(['prefix' => 'sections', 'as' => 'sections.'], function(){
                Route::get('/', 'NewsController@all_sections')->name('all');
                Route::post('new', 'NewsController@create_section')->name('create');
                Route::delete('{id}', 'NewsController@delete_section')->name('delete');
            });
        });

        //Объявления
        Route::group(['prefix' => 'ads', 'as' => 'ads.'], function(){
            Route::get('all', 'AdsController@all')->name('all');
            Route::get('/', 'AdsController@new')->name('new');
            Route::get('edit/{id}', 'AdsController@edit')->name('edit');
            Route::delete('{id}', 'AdsController@delete')->name('delete');
            //Категории объявлений
            Route::group(['prefix' => 'categories', 'as' => 'categories.'], function(){
                Route::get('/', 'AdsController@all_categories')->name('all');
                Route::post('/', 'AdsController@create_category')->name('create');
                Route::delete('{id}', 'AdsController@delete_category')->name('delete');
            });
            //Города объявлений
            Route::group(['prefix' => 'cities', 'as' => 'cities.'], function(){
                Route::get('/', 'AdsController@all_cities')->name('all');
                Route::post('new', 'AdsController@create_city')->name('create');
                Route::delete('{id}', 'AdsController@delete_city')->name('delete');
            });
        });

        //Мероприятия
        Route::group(['prefix' => 'events', 'as' => 'events.'], function(){
            Route::get('all', 'EventsController@all')->name('all');
            Route::get('/', 'EventsController@new')->name('new');
            Route::post('/', 'EventsController@create')->name('create');
            Route::get('edit/{id}', 'EventsController@edit')->name('edit');
            Route::put('edit/{id}', 'EventsController@update')->name('update');
            Route::delete('{id}', 'EventsController@delete')->name('delete');

            //Категории мероприятий
            Route::group(['prefix' => 'categories', 'as' => 'categories.'], function(){
                Route::get('/', 'EventsController@all_categories')->name('all');
                Route::post('/', 'EventsController@create_category')->name('create');
                Route::get('{id}', 'EventsController@edit_category')->name('edit');
                Route::put('{id}', 'EventsController@update_category')->name('update');
                Route::delete('{id}', 'EventsController@delete_category')->name('delete');
            });

            //Секции новостей
            Route::group(['prefix' => 'sections', 'as' => 'sections.'], function(){
                Route::get('/', 'EventsController@all_sections')->name('all');
                Route::post('new', 'EventsController@create_section')->name('create');
                Route::delete('{id}', 'EventsController@delete_section')->name('delete');
            });
        });

        //Пользователи
        Route::group(['prefix' => 'users', 'as' => 'users.'], function() {
            Route::get('/', 'UsersController@all')->name('all');
            Route::get('edit/{id}', 'UsersController@edit')->name('edit');
            Route::put('edit/{id}', 'UsersController@update')->name('update');
            Route::delete('delete/{id}', 'UsersController@delete')->name('delete');
        });

        //Группы
        Route::group(['prefix' => 'groups', 'as' => 'groups.'], function() {

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    protected $connection = 'mysql2';
    protected $table = 'stat';
    protected $primaryKey = 'shortguid';
    public $incrementing = false;
    public $timestamps = false;

    protected $fillable = [
        'name', 'email', 'password', 'first_name', 'last_name', 'middle_name', 'date_birth', 'photo_id'
    ];

    protected $hidden = [
        'password', 'remember_token', 'user_pswd'
    ];

    public $dates = [
        'date_birth'
    ];

    public function getIdAttribute()
    {
        return $this->shortguid;
    }

    public function group()
    {
        return $this->belongsTo(Group::class);
    }

    public function hasPermission($permission)
    {
        if($this->group_id == 0) return false;
        return $this->group->hasPermission($permission);
    }

    public function moneys()
    {
        return \DB::connection('mysql2')->table('moneys')->where('user_name', $this->shortguid)->get();
    }

    public function tariffs()
    {
        return \DB::connection('mysql2')->table('tarifs')->get();
    }

    public function city()
    {
        return $this->setConnection('mysql')->belongsTo(City::class);
    }

    public function files()
    {
        return $this->connection('mysql')->hasMany(\App\Archive\File::class);
    }

    public function getPhotoAttribute()
    {
        return $this->photo_id;
    }

    public function getTitleDevice($ip)
    {
        $device = \App\Device::find($ip);
        if($device) {
            return $device->title;
        }
        return '';
    }

    public function getDevicesAttribute()
    {
        $devices = explode(';', $this->usrip);
        $collect = collect();
        foreach ($devices as $key => $item) {
            $device = null;
            if($item != '' && $item != null) {
                $device = \App\Device::find($item);
                $traffic = $this->getTrafficDevice($key);
                $n = [
                    'ip' => $item,
                    'title' => $device ? $device->title : 'Без названия',
                    'type' => $device ? $device->type : 0,
                    'traffic' => isset($traffic[$key]) ? $traffic[$key] : 0
                ];
                $collect = $collect->push($n);
            }
        }
        return $collect;
    }

    public function getTrafficDevice()
    {
        $startDate = now()->subMonth();
        $endDate = now();
        $traffics = [];
        while($startDate < $endDate) {
            if(\Schema::connection('mysql2')->hasTable('trafflow2_'.$startDate->format('Y-m-d'))) {
                $traff[] = \DB::connection('mysql2')->select('SELECT acc_index, SUM(trafsize) AS result FROM  ' . '`trafflow2_'
                    .$startDate->format('Y-m-d') . '` WHERE usr = 2198716 GROUP BY acc_index');
                foreach ($traff as $key => $day) {
                    foreach ($day as $device) {
                        $traffics[$device->acc_index] = isset($traffics[$device->acc_index]) ?
                            $traffics[$device->acc_index] + $device->result : $device->result;
                    }
                }
            }
            $startDate = $startDate->addDay();
        }
        return $traffics;
    }

    public function getTarifAttribute()
    {
        return \DB::connection('mysql2')->table('tarifs')->where('tarif_guid', $this->tarif_guid)->first();
    }

    public function getChangeTariffsAttribute()
    {
        $tariffs = explode('||', $this->tarif->followingtarifs);
        foreach ($tariffs as $tariff) {
            $return[] = \DB::connection('mysql2')->table('tarifs')->where('tarif_name', $tariff)->first();
        }
        return collect($return);
    }
}

app/Http/Controllers/AdministrationController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class AdministrationController extends Controller
{
    public function index()
    {
        return view('administration.index');
    }

    public function complaint()
    {
        return view('administration.complaint');
    }

    public function measures()
    {
        $measures = \App\Measure::orderBy('created_at', 'desc')->get();
        return view('administration.measures', compact('measures'));
    }

    public function measure($id)
    {
        $measure = \App\Measure::find($id);
        $like = \App\Like::hasLike($measure);
        return view('administration.measure', compact('measure', 'like'));
    }
}

resources/views/administration/complaint.blade.php
@extends('layouts.app')

@section('title')
    Новости
@endsection

@section('content')
    <div class="d-flex align-items-center mb-3">
        <h2 class="m-0">Жалобы и предложения</h2>
    </div>
    <div class="row mb-4">
        <div class="col-12">
            <div class="white complaint-form">
                <div class="img"></div>
                <div class="content">
                    <h3>Заполните форму и мы рассмотрим вашу заявку</h3>
                    <form action="{{ route('administration.mail_to_administration') }}" method="post">
                        @csrf
                        <div class="row">
                            <div class="col-12 mb-4">
                                <input type="text" name="theme" placeholder="Тема вашей заявки" required>
                            </div>
                            <div class="col-12 mb-4">
                                <div class="row">
                                    <div class="col-4">
                                        <input type="text" class="phone" name="phone" placeholder="Номер телефона" required>
                                    </div>
                                    <div class="col-4">
                                        <input type="email" name="email" placeholder="Email">
                                    </div>
                                </div>
                            </div>
                            <div class="col-6 mb-4">
                                <input type="text" name="name" placeholder="Имя" required>
                            </div>
                            <div class="col-6 mb-4">
                                <input type="text" name="surname" placeholder="Фамилия" required>
                            </div>
                            <div class="col-12 mb-4">
                                <textarea class="autosize" name="message" rows="8" placeholder="Подробное описание" required></textarea>
                            </div>
                            <div class="col-12">
                                <button type="submit" name="button" class="button blue">Отправить</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/administration/index.blade.php
@extends('layouts.app')

@section('title')
    Новости
@endsection

@section('content')
    <div class="d-flex align-items-center mb-3">
        <h2 class="m-0">Администрация</h2>
    </div>
    <div class="row administration">
        <div class="col-6 col-md-3 mb-4 hover">
            <a href="#">
                <div class="white block">
                    <div class="content">
                        <i class="icon video"></i>
                    </div>
                </div>
            </a>
            <div class="d-block px-1">
                <a href="#">Официальный видео канал МО “Булунский улус(район)”</a>
            </div>
        </div>
        <div class="col-6 col-md-3 mb-4 hover">
            <a href="{{ route('administration.complaint') }}">
                <div class="white block">
                    <div class="content">
                        <i class="icon complaint"></i>
                    </div>
                </div>
            </a>
            <div class="d-block px-1">
                <a href="{{ route('administration.complaint') }}">Подача жалоб и предложений</a>
            </div>
        </div>
        <div class="col-6 col-md-3 mb-4 hover">
            <a href="{{ route('administration.measure.index') }}">
                <div class="white block">
                    <div class="content">
                        <i class="icon measures"></i>
                    </div>
                </div>
            </a>
            <div class="d-block px-1">
                <a href="{{ route('administration.measure.index') }}">Меры поддержки населения и организации</a>
            </div>
        </div>
        <div class="col-6 col-md-3 mb-4 hover">
            <a href="#">
                <div class="white block">
                    <div class="content">
                        <i class="icon copy-site"></i>
                    </div>
                </div>
            </a>
            <div class="d-block px-1">
                <a href="#">Копия муниципального сайта</a>
            </div>
        </div>
    </div>
@endsection

resources/views/administration/measure.blade.php
@extends('layouts.app')

@section('title')
    {{ $measure->title }}
@endsection

@section('content')
    <div class="fullnews white @if($measure->files) mb-3 @else mb-5 @endif">
        <div class="header" style="background-image: url('{{ Storage::url($measure->image) }}')">
            <div class="absolute">
                <div class="info d-flex align-items-center">
                    <span class="date mr-3">{{ $measure->created_at->format('d.m.Y') }}</span>
                    <span class="time">{{ $measure->created_at->format('H:i') }}</span>
                </div>
                <h1 class="little">
                    {{ $measure->title }}
                </h1>
                <hr>
                <div class="stats d-flex align-items-center">
                    <span class="mr-3 d-flex align-items-center"><i class="icon read min"></i>{{ $measure->reads }}</span>
                    <span class="d-flex align-items-center"><i class="icon profile min"></i>@if($measure->user){{ $measure->user->first_name }} {{ $measure->user->last_name }}@endif</span>
                </div>
            </div>
            <a href="#"class="share"></a>
        </div>
        <div class="content">
            {!! html_entity_decode($measure->content) !!}
            <div class="info d-flex align-items-center justify-content-between">
                <div class="profile">
                    <div class="img">
                        <img src="@if($measure->user && $measure->user->photo){{ Storage::url($measure->user->photo) }}@else{{ asset('images/noavatar.jpg') }}@endif" alt="">
                    </div>
                    <span class="name">@if($measure->user){{ $measure->user->first_name }} {{ $measure->user->last_name }}@endif</span>
                </div>
                <div class="d-flex align-items-center">
                    <i class="icon like @auth click @if($like) active @endif @endauth" @auth data-class="{{ get_class($measure) }}" data-id="{{ $measure->id }}" data-user="{{ Auth::user()->id }}" @endauth></i><span>{{ $measure->likes->count() }}</span>
                    <i class="icon read min gray ml-4"></i>{{ $measure->reads }}
                </div>
            </div>
        </div>
    </div>
    @if($measure->files)
        <div class="white mb-4 poll">
            <div class="header">
                <div class="title">
                    Файлы
                </div>
            </div>
            <div class="content">
                <ul class="list-group">
                  @foreach ($measure->files as $key => $file)
                      <li class="list-group-item m-0"><img src="/images/filetype/{{ $file->extension }}.svg" style="max-width: 30px; margin-right: 10px;" alt="{{ $file->extension }}"><a href="{{ route('download_file', ['id' => $file->id]) }}">{{ $file->title }}</a></li>
                  @endforeach
                </ul>
            </div>
        </div>
    @endif
@endsection

resources/views/administration/measures.blade.php
@extends('layouts.app')

@section('title')
    Муниципальные программы
@endsection

@section('content')
    <div class="d-flex align-items-center justify-content-between">
        <h2>Муниципальные программы</h2>
    </div>
    <div class="row news">
        <div class="col-12">
            <div class="row">
                @if($measures->count() == 0)
                    <p>Муниципальных программ нет</p>
                @else
                    @foreach ($measures as $key => $measure)
                        <div class="block flex-sm-row flex-column d-flex white">
                            <div class="image p-3" style="background-image: url('{{ Storage::url($measure->image) }}')">
                            </div>
                            <div class="content">
                                <div class="title">
                                    <a href="{{ route('administration.measure.show', ['id' => $measure->id]) }}">{{ $measure->title }}</a>
                                </div>
                                <div class="short">
                                    {{ $measure->short }}
                                </div>
                                <div class="info d-flex justify-content-between align-items-center py-3">
                                    <span class="time">{{ $measure->created_at->format('d.m.Y в H:i') }}</span>
                                    <div class="d-flex stats align-items-center">
                                        <i class="icon read"></i>{{ $measure->read }}<i class="icon comments ml-4"></i>0
                                    </div>
                                </div>
                            </div>
                        </div>
                    @endforeach
                @endif
            </div>
        </div>
    </div>
@endsection