routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'PageController@index')->name('index');

//Новости
Route::group(['namespace' => 'News', 'as' => 'news.', 'prefix' => 'news'], function() {
    Route::get('/', 'NewsController@index')->name('index');
    Route::get('section/{id}', 'NewsController@section')->name('section');
    Route::post('add', 'NewsController@create')->name('create');
    Route::post('test', 'NewsController@test')->name('test');
    Route::put('update/{id}', 'NewsController@update')->name('update');
    Route::get('{id}', 'NewsController@news')->name('news');
});

//Объявления
Route::group(['namespace' => 'Ad', 'as' => 'ads.', 'prefix' => 'ads'], function() {
    Route::get('/', 'AdController@index')->name('index');
    Route::get('add', 'AdController@add')->name('add');
    Route::post('add', 'AdController@create')->name('create');
    Route::put('edit/{id}', 'AdController@update')->name('update');
    Route::get('category/{category_id}', 'AdController@category')->name('category');
    Route::get('ad/{id}', 'AdController@ad')->name('ad');
});

// Мероприятния
Route::group(['namespace' => 'Event', 'as' => 'events.', 'prefix' => 'events'], function() {
    Route::get('/', 'EventController@index')->name('index');
    Route::get('section/{section_id}', 'EventController@section')->name('section');
    Route::get('event/{id}', 'EventController@event')->name('event');
});

//Форум
Route::group(['as' => 'forum.', 'prefix' => 'forum', 'namespace' => 'Forum'], function() {
    Route::get('/', 'TopicController@index')->name('index');
    Route::get('add', 'TopicController@add')->name('add');
    Route::post('add', 'TopicController@create')->name('create');
    Route::get('topic/{id}', 'TopicController@topic')->name('topic');
    Route::post('topic/{id}', 'TopicController@create_message')->name('create_message');
});

Route::get('road', 'PageController@road')->name('road');
Route::get('bus', 'PageController@bus')->name('bus');
Route::get('weather', 'PageController@weather')->name('weather');
Route::get('aero', 'PageController@aero')->name('aero');
Route::get('afisha', 'PageController@afisha')->name('afisha');

//Администрация
Route::group(['as' => 'administration.', 'prefix' => 'administration'], function() {
    Route::get('/', 'AdministrationController@index')->name('index');
    Route::get('complaint', 'AdministrationController@complaint')->name('complaint');
    Route::post('complaint', 'AbuseFormController@mail_to_administration')->name('mail_to_administration');
    Route::group(['prefix' => 'measure', 'as' => 'measure.'], function() {
        Route::get('/', 'AdministrationController@measures')->name('index');
        Route::get('show/{id}', 'AdministrationController@measure')->name('show');
    });
});

//Архив
Route::group(['as' => 'archive.', 'prefix' => 'archive'], function() {
    Route::get('/', 'ArchiveController@index')->name('index');
    Route::get('upload', 'ArchiveController@upload')->name('upload.file');
    Route::get('mayak', 'ArchiveController@mayak')->name('mayak');
    Route::get('mayak/{id}', 'ArchiveController@show_mayak')->name('show_mayak');
    Route::get('add', 'ArchiveController@add')->name('add');
    Route::post('add', 'ArchiveController@create')->name('create');
    Route::get('section/{id}', 'ArchiveController@section')->name('section');
});

//Лк
Route::group(['prefix' => 'lk', 'as' => 'lk.', 'middleware' => 'auth'], function() {
    Route::get('/', 'UserController@index')->name('index');
    Route::put('/', 'UserController@update')->name('update');
    Route::get('news', 'UserController@news')->name('news');
    Route::get('ads', 'UserController@ads')->name('ads');
    Route::get('events', 'UserController@events')->name('events');
    Route::get('balance', 'UserController@balance')->name('balance');
    Route::get('traffic_info', 'UserController@traffic_info')->name('traffic_info');
    Route::get('tariff', 'UserController@tariff')->name('tariff');
    Route::post('tariff', 'UserController@change_tariff')->name('change_tariff');
    Route::get('documents', 'UserController@documents')->name('documents');
    Route::post('yandex_pay', 'UserController@yandex_pay')->name('yandex_pay');
});


Route::post('ckeditor/image_upload', 'CKEditorController@upload')->name('upload.image');
Route::get('download/{id}', 'PageController@download_file')->name('download_file');

Route::group(['prefix' => 'comment', 'as' => 'comment.'], function() {
    Route::post('add', 'CommentController@create')->name('create');
});

//Админка
Route::group(['prefix' => 'admin', 'as' => 'admin.'], function(){
    Route::get('/', 'AdminController@index')->name('index');

    Route::group(['namespace' => 'Admin'], function() {
        //Новости
        Route::group(['prefix' => 'news', 'as' => 'news.'], function() {
            Route::get('all', 'NewsController@all')->name('all');
            Route::get('/', 'NewsController@new')->name('new');
            Route::get('edit/{id}', 'NewsController@edit')->name('edit');
            Route::delete('{id}', 'NewsController@delete')->name('delete');
            //Категории новостей
            Route::group(['prefix' => 'category', 'as' => 'category.'], function(){
                Route::get('/', 'NewsController@all_categories')->name('all');
                Route::post('/', 'NewsController@create_category')->name('create');
                Route::get('{id}', 'NewsController@edit_category')->name('edit');
                Route::put('{id}', 'NewsController@update_category')->name('update');
                Route::delete('{id}', 'NewsController@delete_category')->name('delete');
            });
            //Теги новостей
            Route::group(['prefix' => 'tags', 'as' => 'tags.'], function(){
                Route::get('/', 'NewsController@all_tags')->name('all');
                Route::post('new', 'NewsController@create_tag')->name('create');
                Route::delete('{id}', 'NewsController@delete_tag')->name('delete');
            });
            //Секции новостей
            Route::group(['prefix' => 'sections', 'as' => 'sections.'], function(){
                Route::get('/', 'NewsController@all_sections')->name('all');
                Route::post('new', 'NewsController@create_section')->name('create');
                Route::delete('{id}', 'NewsController@delete_section')->name('delete');
            });
        });

        //Объявления
        Route::group(['prefix' => 'ads', 'as' => 'ads.'], function(){
            Route::get('all', 'AdsController@all')->name('all');
            Route::get('/', 'AdsController@new')->name('new');
            Route::get('edit/{id}', 'AdsController@edit')->name('edit');
            Route::delete('{id}', 'AdsController@delete')->name('delete');
            //Категории объявлений
            Route::group(['prefix' => 'categories', 'as' => 'categories.'], function(){
                Route::get('/', 'AdsController@all_categories')->name('all');
                Route::post('/', 'AdsController@create_category')->name('create');
                Route::delete('{id}', 'AdsController@delete_category')->name('delete');
            });
            //Города объявлений
            Route::group(['prefix' => 'cities', 'as' => 'cities.'], function(){
                Route::get('/', 'AdsController@all_cities')->name('all');
                Route::post('new', 'AdsController@create_city')->name('create');
                Route::delete('{id}', 'AdsController@delete_city')->name('delete');
            });
        });

        //Мероприятия
        Route::group(['prefix' => 'events', 'as' => 'events.'], function(){
            Route::get('all', 'EventsController@all')->name('all');
            Route::get('/', 'EventsController@new')->name('new');
            Route::post('/', 'EventsController@create')->name('create');
            Route::get('edit/{id}', 'EventsController@edit')->name('edit');
            Route::put('edit/{id}', 'EventsController@update')->name('update');
            Route::delete('{id}', 'EventsController@delete')->name('delete');

            //Категории мероприятий
            Route::group(['prefix' => 'categories', 'as' => 'categories.'], function(){
                Route::get('/', 'EventsController@all_categories')->name('all');
                Route::post('/', 'EventsController@create_category')->name('create');
                Route::get('{id}', 'EventsController@edit_category')->name('edit');
                Route::put('{id}', 'EventsController@update_category')->name('update');
                Route::delete('{id}', 'EventsController@delete_category')->name('delete');
            });

            //Секции новостей
            Route::group(['prefix' => 'sections', 'as' => 'sections.'], function(){
                Route::get('/', 'EventsController@all_sections')->name('all');
                Route::post('new', 'EventsController@create_section')->name('create');
                Route::delete('{id}', 'EventsController@delete_section')->name('delete');
            });
        });

        //Пользователи
        Route::group(['prefix' => 'users', 'as' => 'users.'], function() {
            Route::get('/', 'UsersController@all')->name('all');
            Route::get('edit/{id}', 'UsersController@edit')->name('edit');
            Route::put('edit/{id}', 'UsersController@update')->name('update');
            Route::delete('delete/{id}', 'UsersController@delete')->name('delete');
        });

        //Группы
        Route::group(['prefix' => 'groups', 'as' => 'groups.'], function() {

app/Measure.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Measure extends Model
{
    protected $fillable = [
        'title', 'short', 'content', 'user_id'
    ];

    protected $guarded = [
        'image', 'reads'
    ];

    public function comments()
    {
        return $this->morphMany('App\Comment', 'commentable');
    }

    public function likes()
    {
        return $this->morphMany('App\Like', 'liketable');
    }

    public function files()
    {
        return $this->hasMany(MeasureFile::class);
    }

    public function user()
    {
        return $this->belongsTo(User::class, 'user_id', 'shortguid');
    }
}

app/Http/Controllers/Admin/MeasureController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\MeasureFile;
use App\Measure;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\File;

class MeasureController extends Controller
{
    public function index()
    {
        $measures = Measure::orderBy('created_at', 'desc')->get();
        return view('admin.administration.measure.index', compact('measures'));
    }

    public function add()
    {
        return view('admin.administration.measure.add');
    }

    public function create(Request $request)
    {
        $measure = Measure::create($request->all() + ['user_id' => \Auth::check() ? \Auth::user()->id : 1]);
        if($request->has('content')) $measure->content = htmlentities($request->content);
        if($request->hasFile('image')) $measure->image = \Storage::disk('public')->putFile('images', $request->image);
        $measure->save();
        if($request->has('docs')) {
            foreach ($request->docs as $key => $file) {
                $title = $file->getClientOriginalName();
                $extension = $file->getClientOriginalExtension();
                $url = \Storage::disk('public')->putFileAs('files', $file, \Str::random(10).$title);
                $newfile = MeasureFile::create([
                    'title' => $title,
                    'extension' => $extension,
                    'url' => $url,
                    'measure_id' => $measure->id
                ]);
            }
        }

        return redirect(route('admin.administration.measure.index'))->with('success', 'Успешно добавлено');
    }

    public function edit($id)
    {
        $measure = Measure::find($id);
        return view('admin.administration.measure.edit', compact('measure'));
    }

    public function update(Request $request, $id)
    {
        $measure = Measure::find($id);
        $measure->update($request->all());
        if($request->has('content')) $measure->content = htmlentities($request->content);
        if($request->hasFile('image')) {
            if($measure->image) \Storage::delete($measure->image);
            $measure->image = \Storage::disk('public')->putFile('images', $request->image);
        }
        if($request->has('docs')) {
            if($measure->files) {
                foreach ($measure->files as $key => $file) {
                    \Storage::delete($file->url);
                    $file->delete();
                }
            }
            foreach ($request->docs as $key => $file) {
                $title = $file->getClientOriginalName();
                $extension = $file->getClientOriginalExtension();
                $url = \Storage::disk('public')->putFileAs('files', $file, \Str::random(10).$title);
                $newfile = MeasureFile::create([
                    'title' => $title,
                    'extension' => $extension,
                    'url' => $url,
                    'measure_id' => $measure->id
                ]);
            }
        }
        $measure->save();
        return redirect(route('admin.administration.measure.index'))->with('success', 'Успешно обновлено');
    }

    public function delete($id)
    {
        $measure = Measure::find($id);
        foreach ($measure->files as $key => $file) {
            \Storage::delete($file->url);
            $file->delete();
        }
        if($measure->image) \Storage::delete($measure->image);
        $measure->delete();

        return redirect(route('admin.administration.measure.index'))->with('success', 'Успешно удалено');
    }
}

app/Http/Controllers/AdministrationController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class AdministrationController extends Controller
{
    public function index()
    {
        return view('administration.index');
    }

    public function complaint()
    {
        return view('administration.complaint');
    }

    public function measures()
    {
        $measures = \App\Measure::orderBy('created_at', 'desc')->get();
        return view('administration.measures', compact('measures'));
    }

    public function measure($id)
    {
        $measure = \App\Measure::find($id);
        $like = \App\Like::hasLike($measure);
        return view('administration.measure', compact('measure', 'like'));
    }
}

resources/views/admin/administration/measure/add.blade.php
@extends('layouts.admin')

@section('title')
    Добавление новости - АдминПанель - Булунский Портал
@endsection

@section('content')
    <div class="container my-2">
        <div class="col-12">
            <form action="{{route('admin.administration.measure.create')}}" method="post" enctype="multipart/form-data">
                @csrf
                <div class="form-group">
                    <label>Заголовок</label>
                    <input type="text" name="title" class="form-control" placeholder="Введите заголовок" required>
                </div>
                <div class="form-group">
                    <label>Короткое описание</label>
                    <textarea name="short" class="form-control" required></textarea>
                </div>
                <div class="form-group">
                    <label>Полное описание</label>
                    <textarea name="content" id="content" required></textarea>
                </div>
                <div class="form-group">
                    <label>Изображение</label>
                    <input type="file" name="image" class="form-control-file" required>
                </div>
                <div class="form-group">
                    <label>Файлы <span class="badge badge-secondary">Выберите все необходимые файлы</span></label>
                    <input type="file" name="docs[]" class="form-control-file" required multiple>
                </div>
                <button type="submit" class="btn btn-primary">Добавить</button>
            </form>
            <script src="{{ asset('js/ckeditor/ckeditor.js') }}"></script>
            <script>
                CKEDITOR.replace( 'content', {
                    filebrowserUploadUrl: "{{route('upload.image', ['_token' => csrf_token() ])}}",
                    filebrowserUploadMethod: 'form'
                });
            </script>
        </div>
    </div>
@endsection

resources/views/admin/administration/measure/edit.blade.php
@extends('layouts.admin')

@section('title')
    Добавление новости - АдминПанель - Булунский Портал
@endsection

@section('content')
    <div class="container my-2">
        <div class="col-12">
            <form action="{{route('admin.administration.measure.update', ['id' => $measure->id])}}" method="post" enctype="multipart/form-data">
                @csrf
                @method('put')
                <div class="form-group">
                    <label>Заголовок</label>
                    <input type="text" name="title" class="form-control" value="{{ $measure->title }}" placeholder="Введите заголовок" required>
                </div>
                <div class="form-group">
                    <label>Короткое описание</label>
                    <textarea name="short" class="form-control" required>{{ $measure->short }}</textarea>
                </div>
                <div class="form-group">
                    <label>Полное описание</label>
                    <textarea name="content" id="content" required>{!!  html_entity_decode($measure->content) !!}</textarea>
                </div>
                <div class="form-group">
                    @if($measure->image)<img src="{{ Storage::url($measure->image) }}" style="max-width: 200px;" alt=""><br>@endif
                    <label>Изображение <span class="badge badge-secondary">выберите чтобы изменить текущее</span></label>
                    <input type="file" name="image" class="form-control-file">
                </div>
                <div class="form-group">
                    <label>Файлы <span class="badge badge-secondary">Можно выбрать несколько (предыдущие будут удалены)</span></label>
                    <input type="file" name="docs[]" class="form-control-file" multiple>
                    @if($measure->files)
                        <div class="d-block"><b>Сейчас прикреплены</b></div>
                        <ul class="list-group">
                            @foreach ($measure->files as $key => $file)
                                <li class="list-group-item"><img src="/images/filetype/{{ $file->extension }}.svg" style="max-width: 30px;margin-right: 10px;" alt="">{{ $file->title }}</li>
                            @endforeach
                        </ul>
                    @endif
                </div>
                <button type="submit" class="btn btn-primary">Обновить</button>
            </form>
            <script src="{{ asset('js/ckeditor/ckeditor.js') }}"></script>
            <script>
                CKEDITOR.replace( 'content', {
                    filebrowserUploadUrl: "{{route('upload.image', ['_token' => csrf_token() ])}}",
                    filebrowserUploadMethod: 'form'
                });
            </script>
        </div>
    </div>
@endsection

resources/views/admin/administration/measure/index.blade.php
@extends('layouts.admin')

@section('title')
    Меры поддержки - АдминПанель - Булунский Портал
@endsection

@section('content')
    <div class="table-responsive">
        <table class="table table-sm">
            <thead class="thead-dark">
                <tr>
                    <th scope="col">#</th>
                    <th scope="col">Название</th>
                    <th scope="col"></th>
                </tr>
            </thead>
            <tbody>
                @if($measures->count() != 0)
                    @foreach ($measures as $key => $measure)
                        <tr>
                            <td scope="col" class="align-middle">{{$measure->id}}</td>
                            <td class="align-middle">{{$measure->title}}</td>
                            <td class="align-middle text-right">
                                <div class="d-flex justify-content-end">
                                    <a href="{{route('admin.administration.measure.edit', ['id' => $measure->id])}}" role="button" class="btn btn-sm btn-success"><span class="oi oi-pencil"></span></a>
                                    <form action="{{route('admin.administration.measure.delete', ['id' => $measure->id])}}" method="post">
                                        @csrf
                                        @method('delete')
                                        <button type="sumbit" class="btn btn-danger btn-sm ml-2" onclick="return confirm('Удалить {{$measure->title}}?');">
                                            <span class="oi oi-trash"></span>
                                        </button>
                                    </form>
                                </div>
                            </td>
                        </tr>
                    @endforeach
                @else
                    <tr>
                        <td colspan="3">Мер нет</td>
                    </tr>
                @endif
            </tbody>
        </table>
    </div>
    <a href="{{ route('admin.administration.measure.add') }}" class="btn btn-sm btn-success ml-2">Добавить</a>
@endsection